
name: 'Install Inkscape'
description: "Installs Inkscape on Linux and Windows"
runs:
  using: "composite"
  steps:
  - if: runner.os == 'Windows'
    run: choco install inkscape
    shell: bash
  - if: runner.os == 'Linux'
    run: sudo apt install inkscape
    shell: bash
