
name: 'Install Inkscape'
description: "Installs Inkscape on Linux and Windows"
runs:
  using: "composite"
  steps:
  - if: runner.os == 'Windows'
    shell: bash
    run: choco install inkscape
  - if: runner.os == 'Linux'
    shell: bash
    run: |
      sudo apt update
      sudo apt install inkscape
