[profile.default]
slow-timeout = { period = "30s", terminate-after = 2 }

[profile.ci.junit]  # this can be some other profile, too
path = "junit.xml"
store-success-output = true
store-failure-output = true
